model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 1000 # equal to num_images
  latent_dim: 122
  img_size: 512

data_params:
  data_path: '/home/zhengqi/Diffusion-based-Vide-Codec/Project/Unet-diffusion-based-Video-Compression/images/ffhq_512_n5000/humanface/'
  train_batch_size: 36
  val_batch_size: 36
  patch_size: 64 # useless, since no crop 
  num_workers: 12
  if_encoder: False
  num_images: 1000
  dataset_size: 100000


exp_params:
  LR: 0.00005
  weight_decay: 0.0
  scheduler_type: 'ExponentialLR'  # 'StepLR', 'MultiStepLR'
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 3047
  auto_sample: True
  sample_every_n_steps: 2000

trainer_params:
  gpus: [0]
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE_analyze_weight"