model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 92
  img_size: 256

data_params:
  name: 'n02123045_s256_n1000'
  data_path: '/home/zhengqi/Diffusion-based-Vide-Codec/Dataset/ILSVRC2012_train/n02123045_all/n02123045_s256/'
  train_batch_size: 36
  val_batch_size:  36
  patch_size: 64 # useless, since no crop 
  num_workers: 6
  if_encoder: False
  num_images: 1000
  dataset_size: 100000
  noise_dim: 92  # the same as latent_dim. Used in top_noise


exp_params:
  LR: 0.0002
  weight_decay: 0.0
  scheduler_type: 'ExponentialLR'  # 'StepLR'
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 3047
  auto_sample: True
  sample_every_n_steps: 3000

trainer_params:
  gpus: [0]
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
