model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128
  img_size: 512

data_params:
  data_path: '/home/zhengqi/Diffusion-based-Vide-Codec/Project/Unet-diffusion-based-Video-Compression/images/ffhq_512_n5000/humanface/'
  train_batch_size: 36
  val_batch_size:  36
  patch_size: 64 # useless, since no crop 
  num_workers: 12
  if_encoder: False
  num_images: 1500
  dataset_size: 100000
  noise_dim: 128  # the same as latent_dim. Used in top_noise


exp_params:
  LR: 0.0002
  weight_decay: 0.0
  scheduler_type: 'ExponentialLR'  # 'StepLR'
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 3047
  auto_sample: True
  sample_every_n_steps: 3000

trainer_params:
  gpus: [0]
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
